-- Run this once in Supabase SQL Editor.
-- Creates the table used by the Admin payment form and Trip Expenses balance sheet.

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  from_person text not null,
  to_person text not null,
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  constraint payments_different_people check (from_person <> to_person)
);

alter table public.payments enable row level security;

drop policy if exists "payments_select_public" on public.payments;
create policy "payments_select_public"
on public.payments for select
to anon, authenticated
using (true);

drop policy if exists "payments_insert_authenticated" on public.payments;
create policy "payments_insert_authenticated"
on public.payments for insert
to authenticated
with check (true);

drop policy if exists "payments_delete_authenticated" on public.payments;
create policy "payments_delete_authenticated"
on public.payments for delete
to authenticated
using (true);

grant select on public.payments to anon, authenticated;
grant insert, delete on public.payments to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'payments'
  ) then
    alter publication supabase_realtime add table public.payments;
  end if;
end $$;

notify pgrst, 'reload schema';
